# pubspec.yaml (CONFIGURACIÓN FINAL Y COMENTADA)

name: quiz_app_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

# =======================================================
# === ESTRUCTURA: Dependencias de Producción ===
# =======================================================
dependencies:
  flutter:
    sdk: flutter

  # UI & State Management
  provider: ^6.1.2
  flutter_animate: ^4.5.0
  percent_indicator: ^4.2.3
  cupertino_icons: ^1.0.8

  # Functionality
  audioplayers: ^6.0.0
  shared_preferences: ^2.2.3

# =======================================================
# === ESTRUCTURA: Dependencias de Desarrollo ===
# =======================================================
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# =======================================================
# === ESTRUCTURA: Configuración Específica de Flutter ===
# =======================================================
flutter:
  uses-material-design: true

  # --- CORRECCIÓN CLAVE: Declaración de Assets Explícita ---
  # Se declara cada archivo individualmente. Esta es la forma más robusta
  # de garantizar que Flutter encuentre tus assets, usando los nombres y
  # extensiones correctos de tu repositorio (correct_answer.mp3).
  assets:
    - assets/quizzes.json
    - assets/sounds/correct_answer.mp3
    - assets/sounds/wrong_answer.mp3

  # --- ESTRUCTURA: Fuentes Personalizadas ---
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Italic.ttf
          style: italic
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700